<?php
/**
 * Implements hook_form_FORM_ID_alter().
 * Placeholder settings for search textfield.
 */
function buesti_form_search_admin_settings_alter(&$form, &$form_state, $form_id) {
  $form['placeholder'] = array(
    '#type' => 'fieldset',
    '#title' => t('Placeholder'),
  );
  $form['placeholder']['search_placeholder'] = array(
    '#type' => 'textfield',
    '#title' => t('Placeholder Text'),
    '#default_value' => variable_get('search_placeholder', ''),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Add placeholder attribute to search textfield
 */
function buesti_form_search_block_form_alter(&$form, &$form_state, $form_id) {
  $form['search_block_form']['#attributes']['placeholder'] = variable_get('search_placeholder', '');
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Add placeholder attribute to search textfield
 */
function buesti_form_search_form_alter(&$form, &$form_state, $form_id) {
  $form['basic']['keys']['#attributes']['placeholder'] = variable_get('search_placeholder', '');
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Set correct title at login page
 */
function buesti_form_user_login_alter(&$form, &$form_state, $form_id) {
  drupal_set_title(t('Login'));
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Set correct title at new password page
 */
function buesti_form_user_pass_alter(&$form, &$form_state, $form_id) {
  drupal_set_title(t('Neues Password'));
}

function buesti_init() {
  global $user;
  if (!$user->uid && arg(0) == 'user' && !arg(1)) {
    drupal_goto('user/login');
  }
}